# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: buchhalter-ai

before:
  hooks:
    - go mod tidy

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - binary: buchhalter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -X main.cliVersion={{ .Version }} -X main.commitHash={{ .Commit }} -X main.buildTime={{ .CommitDate }}

# TODO: Think about to verify the mac builds, see https://goreleaser.com/customization/notarize/

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS_
      {{- else }}{{- title .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# TODO Add a proper release message, see https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L383C1-L402C14

# Homebrew (macOS)
brews:
  - repository:
      owner: buchhalter-ai
      name: homebrew-buchhalter
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula

    homepage: "https://buchhalter.ai/"
    description: "Automatically sync all your incoming invoices from your suppliers."

    license: "SSPL-1.0"
    install: |
      bin.install "buchhalter"
    test: |
      system "#{bin}/buchhalter version"
